import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    atoms: 'src/atoms/index.ts',
    'atoms/kintone': 'src/atoms/kintone.ts',
    'atoms/plugin': 'src/atoms/plugin.ts',
    'atoms/ui': 'src/atoms/ui.ts',
    hooks: 'src/hooks/index.ts',
    'hooks/use-array': 'src/hooks/use-array.ts',
    'hooks/array-atoms': 'src/hooks/array-atoms.ts',
    components: 'src/components/index.ts',
    'components/action-multi-select': 'src/components/action-multi-select.tsx',
    'components/action-select': 'src/components/action-select.tsx',
    'components/app-multi-select': 'src/components/app-multi-select.tsx',
    'components/app-select': 'src/components/app-select.tsx',
    'components/dnd-context': 'src/components/dnd-context.tsx',
    'components/field-multi-select': 'src/components/field-multi-select.tsx',
    'components/field-select': 'src/components/field-select.tsx',
    'components/number': 'src/components/number.tsx',
    'components/query-builder': 'src/components/query-builder/index.ts',
    'components/radio': 'src/components/radio.tsx',
    'components/sortable-context': 'src/components/sortable-context.tsx',
    'components/status-multi-select': 'src/components/status-multi-select.tsx',
    'components/status-select': 'src/components/status-select.tsx',
    'components/switch': 'src/components/switch.tsx',
    'components/text': 'src/components/text.tsx',
    'components/toggle-panel': 'src/components/toggle-panel.tsx',
    'components/view-multi-select': 'src/components/view-multi-select.tsx',
    'components/view-select': 'src/components/view-select.tsx',
  },
  format: ['cjs', 'esm'],
  dts: true,
  clean: true,
  sourcemap: true,
  splitting: true,
  treeshake: true,
  jsx: 'automatic',
  external: [
    'react',
    'react-dom',
    'react/jsx-runtime',
    'jotai',
    'react-error-boundary',
    '@dnd-kit/core',
    '@dnd-kit/modifiers',
    '@dnd-kit/sortable',
    '@konomi-app/kintone-utilities',
    '@mui/icons-material',
    '@mui/material',
    '@radix-ui/react-slot',
  ],
});
